

## Return a List containing 4 functions to access 'x' or the inverse of 'x'
## The four functions contained in the list are
##  set(matrix) - caches 'matrix'
##  get() - return the cached matrix
##  setInverse(inverse) - caches 'inverse'
##  getInverse() - return the cached inverse

makeCacheMatrix <- function(x = matrix()) {
  cachedMatrix <- NULL
  set <- function(matrix) {
    x <<- matrix
    cachedMatrix <<- NULL
  }
  get <- function() x
  setInverse <- function(inverse) cachedMatrix <<- inverse
  getInverse <- function() cachedMatrix
  
  list(set = set, get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}


## Return the inverse of 'cachedMatrix'
## where cachedMatrix is a list generated by makeCacheMatrix
## see makeCacheMatrix for requirements of cachedMatrix

cacheSolve <- function(cachedMatrix, ...) {
        
    inverse <- cachedMatrix$getInverse()
    if(!is.null(inverse)){
      message("getting cached data")
      return(inverse)
    }
    
    data <- cachedMatrix$get()
    inverseMatrix <- solve(data, ...)
    cachedMatrix$setInverse(inverseMatrix)
    inverseMatrix
}
